In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
dataset = pd.read_csv('dataset/train.csv')

In [3]:
dataset.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [4]:
data = np.array(dataset)
m,n = data.shape
print(m,n)
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

42000 785


In [5]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(784, 41000))

In [6]:
X_train[:, 0].shape

(784,)

In [ ]:

#Todo - Research initilization techniques. Came across He initilization for the RELU activation function
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLu(Z):
   return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))
    

def forward_prop(W1,b1,W2,b2, X):
    Z1 = W1 @ X + b1
    A1 = ReLu(Z1)
    Z2 = W2 @ A1 + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLu(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2,X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2 @ A1.T
    db2 = 1 / m * np.sum(dZ2, 2)
    dZ1 = W2.T @ dZ2 * deriv_ReLu(Z1)
    
    dW1 = 1 / m * dZ1 @ X.T
    db1 = 1 / m * np.sum(dZ1, 2)
    return dW1, db1, dW2, db2
    


(array([[ 0.00120335,  0.36130918, -0.3875519 , ...,  0.02285208,
         -0.23906879, -0.41568322],
        [ 0.12520858, -0.4298646 , -0.40522724, ..., -0.17704942,
         -0.31772287, -0.2024802 ],
        [ 0.28193702,  0.23135802,  0.21132714, ...,  0.1417043 ,
          0.36961043,  0.01914953],
        ...,
        [-0.45922775, -0.3953053 , -0.32923925, ..., -0.38929558,
         -0.47105776,  0.34065817],
        [-0.34732298,  0.49918754, -0.48895857, ..., -0.00718126,
         -0.03992411, -0.40906418],
        [-0.02398279, -0.03637585,  0.05951366, ..., -0.2686634 ,
         -0.15299809,  0.30489637]], shape=(10, 784)),
 array([[ 0.0608918 ],
        [ 0.21296992],
        [-0.34752251],
        [-0.06431698],
        [ 0.02378696],
        [-0.00777401],
        [-0.26962455],
        [-0.06502   ],
        [-0.20604022],
        [ 0.18176681]]),
 array([[-2.07935993e-01, -1.64003119e-01, -2.06047442e-01,
          1.06889219e-01,  1.56378243e-01, -4.62795762e-02,
    